blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Request a feature
    url: https://github.com/btcpayserver/btcpayserver/discussions/categories/ideas-feature-requests
    about: Submit a feature request or vote on ideas posted by others. Features with most upvotes become roadmap candidates
  - name: ğŸ§‘â€ğŸ’» Ask a technical question
    url: https://github.com/btcpayserver/btcpayserver/discussions/new?category=technical-support
    about: If you're experiencing a technical problem post it to our community support forum
  - name: ğŸ”Œ Report a problem with a plugin
    url: https://github.com/btcpayserver/btcpayserver/discussions/new?category=plugins-integrations
    about: Experiencing a problem with a third-party plugin? Post it here and we will tag their developers to assist
  - name: ğŸ“ Official Documentation
    url: https://docs.btcpayserver.org
    about: Check our documentation for answers to common questions
  - name: ğŸ’¬ Community Support Chat
    url: https://chat.btcpayserver.org/
    about: Ask general questions and get community support in real-time
